title: Jason A. Dolorso # your name (or website title) here
logo: "/images/portrait3.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Under construction. 
  <br><br>
  ETA Feb 12, 2021.
  
  
  A Petroleum Engineer turned Data Scientist with an endless pursuit of knowledge and growth, leading to diverse experience in the fields of Energy, Global Supply Chain, and Analytics. Currently taking MSc in Data Science at the Asian Institute of Management with the goal of further equipping myself to empower organizations in making data-driven decisions and pioneer Data Science in the Philippines. 
  <br><br>
  <a href="https://www.linkedin.com/in/jasondolorso/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
