title: <p align="center"> Jason Dolorso </p>
logo: "/images/portrait3.png?raw=true" # your photo (or logo) here
description:
  <p align="center">
  <a href="pdf/CV - Dolorso, Jason.pdf">Resume</a>  |
  <a href="https://www.linkedin.com/in/jasondolorso/">LinkedIn</a>
  
  <br><br>
  Data Scientist at <a href="https://www.se.com/ww/en/">Schneider Electric</a> 
  <br>
  MS in Data Science at <br><a href="https://www.aim.edu/">AIM</a>
  </p>
  
  <p align="justify">
  A Petroleum Engineer turned Data Scientist with the goal of empowering organizations in making data-driven decisions.
  Currently a Data Scientist for the <a href="https://www.se.com/ww/en/about-us/newsroom/news/press-releases/schneider-electric-ranked-world%E2%80%99s-most-sustainable-company-by-corporate-knights-600a99142da98a304f239fbf">world's most sustainable company</a>.
  </p>

theme: jekyll-theme-minimal
google_analytics: UA-190336665-1 # your Google Analytics tracking ID here
