title: <p align="center"> Jason Dolorso </p>
logo: "/images/portrait3.png?raw=true" # your photo (or logo) here
description:
  <p align="center">
  <a href="pdf/CV - Dolorso, Jason.pdf">Resume</a>  |
  <a href="https://www.linkedin.com/in/jasondolorso/">LinkedIn Profile</a>
  </p>
  
  <p align="justify">
  A Petroleum Engineer turned Data Scientist with the goal of empowering organizations in making data-driven decisions.
  <br><br>
  I am currently taking MS in Data Science at Asian Institute of Management.
  <br><br>
  </p>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
